pumaeventos/Eventos/urls.py
from django.urls import path
from .views import *

app_name = 'Eventos'
urlpatterns = [
    path('CrearEvento/', CrearEvento.as_view(), name = 'IHCrearEvento'),
    path('ListarEventos/', ListarEventos.as_view(), name = 'IHListarEventos'),
    path('Busqueda/', Busqueda.as_view(), name = 'IHBusqueda'),
]

pumaeventos/Home/urls.py
from django.urls import path

from . import views

urlpatterns = [
    #Home page
    path('', views.home_page, name='home_page'),
]

pumaeventos/Usuarios/urls.py
from django.urls import path
from .views import SignUpView, BienvenidaView, SignInView, SignOutView

app_name = "Usuarios"

urlpatterns = [
    path('', BienvenidaView.as_view(), name='bienvenida'),
    path('registrate/', SignUpView.as_view(), name='sign_up'),
    path('inicia-sesion/', SignInView.as_view(), name='sign_in'),
    path('cerrar-sesion', SignOutView.as_view(), name='sign_out'),
    ]

pumaeventos/pumaeventos/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('Usuarios.urls','Usuarios'))),
    path('', include(('Eventos.urls','Eventos')))
]

pumaeventos/Eventos/models.py
import django
from django.db import models

# Create your models here.
"""
1. Ver como definir cada campo
2. ver el metodo __str__
3. Metodos personalizados
4. Ver campos relacionados
Nota;arroja un error en la migracion por los cambios a los modelos.
"""


"""
    Evento
"""


class Evento(models.Model):

    id_evento = models.CharField(max_length=100, primary_key=True, unique=True)
    id_organizador = models.CharField(max_length=100)
    nombre_evento = models.CharField(max_length=100)
    ubicacion = models.TextField()
    detalles_evento = models.TextField()
    cupo = models.IntegerField()
    fecha_inicio_evento = models.DateField(default=django.utils.timezone.now,null=False)
    fecha_fin_evento = models.DateField(default=django.utils.timezone.now,null=False)


    def __str__(self):
        return self.nombre_evento

pumaeventos/Home/models.py
import django
from django.db import models

pumaeventos/Usuarios/models.py
from django.db import models

# Create your models here.
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver


class Usuario(models.Model):
    usuario = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.CharField(max_length=255, blank=True)
    web = models.URLField(blank=True)
    id_evento = models.CharField(max_length=100)
    nombre_usuario = models.CharField(max_length=150, unique=True)
    correo_usuario = models.EmailField(max_length=150, unique=True)
    contraseña_usuario = models.CharField(max_length=40)
    confirmacion_usuario = models.BooleanField(default=False)
    statf = models.BooleanField(default=False)
    sexo_usuario = models.CharField(max_length=200)
    pasatiempos_usuario = models.TextField(help_text='Redacta tus pasatiempos')
    entidad_academica_usuario = models.CharField(max_length=100)
    foto_usuario = models.ImageField(upload_to='posts', null=True)


    # Python 3
    def __str__(self):
        return self.usuario.username


@receiver(post_save, sender=User)
def crear_usuario_perfil(sender, instance, created, **kwargs):
    if created:
        print("post_save")
        #Usuario.objects.create(usuario=instance)

pumaeventos/Eventos/forms.py
from django import forms

from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from .models import Evento

class EventoForm(forms.ModelForm):
    class Meta:
        model = Evento
        fields = ('nombre_evento', 'ubicacion', 'detalles_evento','cupo', 'fecha_inicio_evento', 'fecha_fin_evento')

pumaeventos/Usuarios/forms.py
from django import forms


from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from .models import Usuario


class RegistroForm(forms.ModelForm):
    class Meta:
        model = Usuario
        fields = ('nombre_usuario', 'correo_usuario', 'contraseña_usuario',
        'confirmacion_usuario', 'sexo_usuario', 'pasatiempos_usuario',
        'entidad_academica_usuario', 'foto_usuario',)

pumaeventos/Eventos/views.py
#Cambiar el nombre de los view
from django.shortcuts import render,redirect
from django.core.exceptions import ObjectDoesNotExist
from django.views.generic import View,TemplateView,ListView,UpdateView,CreateView,DeleteView
from django.urls import reverse_lazy

from .forms import EventoForm
from .models import Evento
from django.db.models import Q
from django.shortcuts import render_to_response
#from .filters import EventosFiltro

# Create your views here.


class CrearEvento(CreateView):
    model = Evento
    form_class = EventoForm
    template_name = "Eventos/IHCrearEvento.html"
    success_url = reverse_lazy('Eventos:IHListarEventos')


class ActualizarEvento(UpdateView):
    model = Evento
    form_class = EventoForm
    template_name = "Eventos/IHCrearEvento.html"
    success_url = reverse_lazy('Eventos:IHListarEventos')


class ListarEventos(ListView):
    model = Evento
    form_class = EventoForm
    template_name = "Eventos/IHListarEventos.html"
    context_object_name = 'eventos'

class Busqueda(ListView):
    model = Evento
    form_class = EventoForm
    template_name = "Eventos/IHBusqueda.html"
    context_object_name = 'eventos'

    def Busqueda(request):
        query = request.GET.get('q', '')
        if query:
            qset = (
                Q(nombre_evento__icontains=query) |
                Q(detalles_evento__icontains=query)
            )
            results = Evento.objects.filter(qset).distinct()
        else:
            results = []
        return render_to_response("Eventos/IHPrincipal.html", {
            "results": results,
            "query": query
        })

pumaeventos/Home/views.py
from django.shortcuts import render

#Home page
def home_page(request):
    return render(request,'Home/Bienvenida.html')

pumaeventos/Usuarios/views.py
from django.shortcuts import render, redirect

from django.contrib.auth import login, authenticate
from django.views.generic import CreateView, TemplateView
from .models import Usuario
from .forms import RegistroForm
from django.contrib.auth.views import LoginView, LogoutView


class SignUpView(CreateView):
    model = Usuario
    form_class = RegistroForm

    def form_valid(self, form):
        '''
        '''
        user = form.save()
        nuevo_usuario = Usuario(
            usuario=user,
            nombre_usuario=user.username
        )
        nuevo_usuario.save()
        usuario = form.cleaned_data.get('username')
        password = form.cleaned_data.get('password1')
        usuario = authenticate(username=usuario, password=password)
        login(self.request, usuario)
        return redirect('/inicia-sesion')


class BienvenidaView(TemplateView):
    template_name = 'Usuarios/IHPrincipal.html'


class SignInView(LoginView):
    template_name = 'Usuarios/IHinicia_sesion.html'


class SignOutView(LogoutView):
    pass

pumaeventos/Eventos/templates/Eventos/IHBusqueda.html
{% load staticfiles %}
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN">
<html class="no-js" lang="es">
<head>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/normalize.css@8.0.0/normalize.min.css">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/font-awesome@4.7.0/css/font-awesome.min.css">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/lykmapipo/themify-icons@0.1.2/css/themify-icons.css">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/pixeden-stroke-7-icon@1.2.3/pe-icon-7-stroke/dist/pe-icon-7-stroke.min.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.2.0/css/flag-icon.min.css">
  <link rel="stylesheet" href="{% static 'css/cs-skin-elastic.css' %}">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">

    <title>Busqueda{% if query %} Resultados{% endif %}</title>
</head>
<body>
  <h1>Buscar</h1>
  <form action="." method="GET">
    <label for="q">Buscar: </label>
    <input type="text" name="q" value="{{ query|escape }}">
    <input type="submit" value="Buscar">
  </form>

  {% if query %}
    <h2>Resultados para "{{ query|escape }}":</h2>

    {% if results %}
      <ul>
      {% for evento in results %}
        <li>{{ evento|escape }}</li>
      {% endfor %}
      </ul>
    {% else %}
      <p>No se encontraron eventos</p>
    {% endif %}
  {% endif %}
</body>
</html>

pumaeventos/Eventos/templates/Eventos/IHCrearEvento.html
{% extends 'Usuarios/IHPrincipal.html' %}

{% block title %}Lista de Eventos{% endblock %}

{% block body %}
<form action="" method="POST">
  {% csrf_token %}
  {% if error %}
    <h2>{{ error }}</h2>
  {% else %}
      <div class="card">
          <div class="card-header">
              <strong>Crear de Eventos</strong>
          </div>
          <div class="card-body card-block">
              <form action="#" method="post" enctype="multipart/form-data" class="form-horizontal">
                  <div class="row form-group">
                      <div class="col col-md-3">{{ form.nombre_evento.label }}</div>
                      <div class="col-12 col-md-9">{{ form.nombre_evento }}</div>
                  </div>
                  <div class="row form-group">
                      <div class="col col-md-3">{{ form.ubicacion.label }}</div>
                      <div class="col-12 col-md-9">{{ form.ubicacion }}</div>
                  </div>
                  <div class="row form-group">
                      <div class="col col-md-3">{{ form.detalles_evento.label }}</div>
                      <div class="col-12 col-md-9">{{ form.detalles_evento }}</div>
                  </div>
                  <div class="row form-group">
                      <div class="col col-md-3">{{ form.cupo.label }}</div>
                      <div class="col-12 col-md-9">{{ form.cupo }}</div>
                  </div>
                  <div class="row form-group">
                      <div class="col col-md-3">{{ form.fecha_inicio_evento.label }}</div>
                      <div class="col-12 col-md-9">{{ form.fecha_inicio_evento }}</div>
                  </div>
                  <div class="row form-group">
                      <div class="col col-md-3">{{ form.fecha_fin_evento.label }}</div>
                      <div class="col-12 col-md-9">{{ form.fecha_fin_evento }}</div>
                  </div>
                  <div class="text-center">
                      <button type="submit" class="btn btn-primary">Registrar</button>
                      <button type="reset" class="btn btn-danger">Cancelar</button>
                  </div>
              </form>
          </div>
      </div>
  {% endif %}
</form>

{% endblock body %}

pumaeventos/Eventos/templates/Eventos/IHListarEventos.html
{% extends 'Usuarios/IHPrincipal.html' %}

{% block title %}Lista de Eventos{% endblock %}

{% block body %}

  {% if eventos %}
      <div class="card">
          <div class="card-header">
              <strong class="card-title">Listado de Eventos</strong>
          </div>
          <div class="table-stats order-table ov-h">
              <table class="table">
                  <thead>
                      <tr>
                        <th>nombre_evento</th>
                        <th>ubicacion</th>
                        <th>fecha_inicio_evento</th>
                      </tr>
                  </thead>
                  <tbody>
                    {% for evento in eventos %}
                      <tr>
                        <td>{{ evento.nombre_evento }}</td>
                        <td>{{ evento.ubicacion }}</td>
                        <td>{{ evento.fecha_inicio_evento }}</td>
                        <td>
                          <a href="" class="btn btn-primary">Editar</a>
                          <a href="" class="btn btn-danger">Eliminar</a>
                        </td>
                      </tr>
                    {% endfor %}
                  </tbody>
              </table>
          </div>
      </div>
      {% else %}
        <h1>No existen eventos registrados</h1>
      {% endif %}

{% endblock body %}

pumaeventos/Home/templates/Home/Bienvenida.html
<p> Pagina Principal </p>

<p> Aquí iran Registro, inicio de sesion, busqueda y eventos </p>

pumaeventos/Usuarios/templates/Usuarios/IHPrincipal.html
{% load staticfiles %}
{% load bootstrap %}
<!Doctype html>
<html class="no-js" lang="es">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>{% block titulo %}Bienvenido a Puma Eventos {% endblock titulo %}</title>
    <meta name="description" content="Ela Admin - HTML5 Admin Template">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/normalize.css@8.0.0/normalize.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/font-awesome@4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/lykmapipo/themify-icons@0.1.2/css/themify-icons.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/pixeden-stroke-7-icon@1.2.3/pe-icon-7-stroke/dist/pe-icon-7-stroke.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.2.0/css/flag-icon.min.css">
    <link rel="stylesheet" href="{% static 'css/cs-skin-elastic.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

</head>
<body>
<div  class="right-panel">
  <form action="." method="GET">
    <label for="q">Busqueda: </label>
    <input type="text" name="q" value="{{ query|escape }}">
    <input type="submit" value="Buscar">
  </form>
  {% if query %}
    <h2>Resultados para "{{ query|escape }}":</h2>
    {% if results %}
      <ul>
      {% for evento in results %}
        <li>{{ evento|escape }}</li>
      {% endfor %}
      </ul>
    {% else %}
      <p>No se encontraron eventos</p>
    {% endif %}
  {% endif %}
</div>
    <!-- Left Panel -->
    <aside id="left-panel" class="left-panel">
        <nav class="navbar navbar-expand-sm navbar-default">
            <div id="main-menu" class="main-menu">
                <ul class="nav navbar-nav">
                    <li class="active">
                        <a href=""><i class="menu-icon fa fa-laptop"></i>Inicio</a>
                    </li>
                    <li class="menu-item-has-children dropdown">
                       <a href="" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> <i class="menu-icon fa fa-users"></i>Eventos</a>
                       <ul class="sub-menu children dropdown-menu">
                           <li><i class="fa fa-pencil"></i><a href="{% url 'Eventos:IHListarEventos' %}">Listado Eventos</a></li>
                           <li><i class="fa fa-table"></i><a href="{% url 'Eventos:IHCrearEvento' %}">Crear Eventos</a></li>
                       </ul>
                    </li>
                    <li class="menu-item-has-children dropdown">
                       <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> <i class="menu-icon fa fa-book"></i>Usuarios</a>
                       <ul class="sub-menu children dropdown-menu">

                           <li><i class="fa fa-table"></i><a href="">Actividades Usuario</a></li>
                       </ul>
                    </li>
                </ul>
            </div><!-- /.navbar-collapse -->
        </nav>
    </aside>
    <!-- /#left-panel -->
    <!-- Right Panel -->
    <div id="right-panel" class="right-panel">
        <!-- Header-->
        <header id="header" class="header">
            <div class="top-left">
                <div class="navbar-header">
                    <a class="navbar-brand" href="./"><img style="width:800px; height:40px;" src="{% static 'images/logo.png' %}" alt="Logo"></a>
                    <a class="navbar-brand hidden" href="./"><img style="width:800px; height:40px;" src="{% static 'images/logo.png' %}" alt="Logo"></a>
                    <a id="menuToggle" class="menutoggle"><i class="fa fa-bars"></i></a>
                </div>
            </div>
            <div class="top-right">
                <div class="header-menu">
                    <div class="user-area dropdown float-right">
                        <a href="#" class="dropdown-toggle active" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <img class="user-avatar rounded-circle" src="{% static 'images/admin.png' %}" alt="User Avatar">
                        </a>
                        <div class="user-menu dropdown-menu">
                            <a class="nav-link" href="{% url 'Usuarios:sign_in' %}"><i class="fa fa- user"></i>Inicio de Sesion</a>
                            <a class="nav-link" href="{% url 'Usuarios:sign_up' %}"><i class="fa fa -cog"></i>Registro Usuario</a>
                            <a class="nav-link" href="{% url 'Usuarios:sign_out' %}"><i class="fa fa-power -off"></i>Logout</a>
                        </div>
                    </div>

                </div>
            </div>
        </header>

        <div class="content">
            <div class="animated fadeIn">
                <div class="row">
                    <div class="col-lg-12">
                      {% block body %}
                        <div class="col-md-12 prueba">
                            <div class="card bg-primary">
                                <div class="card-body">
                                    <blockquote class="blockquote mb-0 text-light text-center">
                                        <h1 class="text-light">{{ user.username | upper }} Bienvenido a Puma eventos</h1>
                                        <footer class="blockquote-footer text-light">"Puedes encontrar eventos dentro de la UNAM"</footer>
                                    </blockquote>
                                </div>
                            </div>
                        </div>
                      {% endblock body %}
                </div>
            </div>
        </div>
        <!-- /.content -->
        <div class="clearfix"></div>
        <!-- Footer -->
        <footer class="site-footer">
            <div class="footer-inner bg-white">
                <div class="row">
                    <div class="col-sm-6">
                        Copyright &copy; 2018 Artificial Dragons
                    </div>
                    <div class="col-sm-6 text-right">
                        Designed by <a href="https://colorlib.com">Artificial Dragons</a>
                    </div>
                </div>
            </div>
        </footer>
        <!-- /.site-footer -->
    </div>
    <!-- /#right-panel -->

    <!-- Scripts -->
    <script src="https://cdn.jsdelivr.net/npm/jquery@2.2.4/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.4/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/js/bootstrap.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/jquery-match-height@0.7.2/dist/jquery.matchHeight.min.js"></script>
    <script src="{% static 'js/main.js' %}"></script>

</body>
</html>

pumaeventos/Usuarios/templates/Usuarios/IHinicia_sesion.html
{% load staticfiles %}
<!Doctype html>
<html class="no-js" lang="es">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Inicia Sesion | Puma Eventos</title>
    <meta name="description" content="Ela Admin - HTML5 Admin Template">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/normalize.css@8.0.0/normalize.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/font-awesome@4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/lykmapipo/themify-icons@0.1.2/css/themify-icons.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/pixeden-stroke-7-icon@1.2.3/pe-icon-7-stroke/dist/pe-icon-7-stroke.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.2.0/css/flag-icon.min.css">
    <link rel="stylesheet" href="{% static 'css/cs-skin-elastic.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

</head>
<body class="bg-dark">

    <div class="sufee-login d-flex align-content-center flex-wrap">
        <div class="container">
            <div class="login-content">
                <div class="login-logo">
                    <a href="IHPrincipal.html">
                        <img class="align-content" src="images/logo.png" alt="">
                    </a>
                </div>
                <div class="login-form">
                    <form method="POST">
                      {% csrf_token %}
                        <div class="form-group">
                          {% if form.error_messages %}
                              <div class="alert alert-danger alert-dismissible" role="alert">
                                <button type="button" class="close" data-dismiss = "alert" aria-label = "Close">
                                  <span aria-hidden = "true">&times;</span>
                                </button>
                                <strong>Advertencia: Favor de llenar los campos con un usuario y contraseña validos </strong>
                              </div>
                          {% endif %}
                          {{ form.as_p }}
                        </div>
                        <button type="submit" class="btn btn-success btn-flat m-b-30 m-t-30">Iniciar Sesion</button>
                        <a class="nav-link" href="{% url 'Usuarios:sign_up' %}"><i class="fa fa -cog"></i>Aun no tienes cuenta? </a>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/jquery@2.2.4/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.4/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/js/bootstrap.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/jquery-match-height@0.7.2/dist/jquery.matchHeight.min.js"></script>
    <script src="{% static 'js/main.js' %}"></script>

</body>
</html>

pumaeventos/Usuarios/templates/Usuarios/usuario_form.html
{% extends "base.html" %}

{% block title %}Registrate{% endblock %}

{% block content %}
    <form action="" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" name="submit">
    </form>
{% endblock content %}

pumaeventos/Usuarios/templates/base.html
{% load staticfiles %}
<!Doctype html>
<html class="no-js" lang="es">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Inicio de Sesión | Puma Eventos</title>
    <meta name="description" content="Ela Admin - HTML5 Admin Template">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/normalize.css@8.0.0/normalize.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/font-awesome@4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/lykmapipo/themify-icons@0.1.2/css/themify-icons.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/pixeden-stroke-7-icon@1.2.3/pe-icon-7-stroke/dist/pe-icon-7-stroke.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.2.0/css/flag-icon.min.css">
    <link rel="stylesheet" href="{% static 'css/cs-skin-elastic.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

</head>
<body class="bg-dark">

    <div class="sufee-login d-flex align-content-center flex-wrap">
        <div class="container">
            <div class="login-content">
                <div class="login-logo">
                    <a href="index.html">
                        <img class="align-content" src="images/logo.png" alt="">
                    </a>
                </div>
                <div class="login-form">
                    <form method="POST">
                      {% csrf_token %}
                        <div class="form-group">
                          {% if form.error_messages %}
                              <div class="alert alert-danger alert-dismissible" role="alert">
                                <button type="button" class="close" data-dismiss = "alert" aria-label = "Close">
                                  <span aria-hidden = "true">&times;</span>
                                </button>
                                <strong>Advertencia: </strong> {{ form.get_invalid_login_error }}
                              </div>
                          {% endif %}
                          {{ form.as_p }}
                        </div>
                        <button type="submit" class="btn btn-success btn-flat m-b-30 m-t-30">Iniciar Sesión</button>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/jquery@2.2.4/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.4/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/js/bootstrap.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/jquery-match-height@0.7.2/dist/jquery.matchHeight.min.js"></script>
    <script src="{% static 'js/main.js' %}"></script>

</body>
</html>